### PR TITLE
LRDOCS-10255 Explain how to preview Style Books

### PR DESCRIPTION
**Pull request by Alec-Shay**
See: https://issues.liferay.com/browse/LRDOCS-10255

This adds a new section (and screenshot) explaining the new functionality for the preview feature when creating or editing a Style Book.

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hi @Alec-Shay 🥰

This looks good to me! I just would maybe add that the second dropdown shows the four most recently used items, and you have to click the More button to find the rest of them. It may be obvious, but I think it's worth to mention it.

And just for curiosity, why we put `pages` in lowercase and `Page Templates` and the rest of types in uppercase?

Thanks a lot!

**Comment by sandrodw3** [comment]
I just thought that it could also be worth to mention how the preview of fragments works, as it's a bit different from the rest. I'll copy the paragraph I put in the Confluence blog when describing this issue, along with a gif:

> In the case of fragments, the second dropdown shows the available fragment collections. When selecting one, all the fragments belonging to that collection can be previewed at a time. Isn’t it awesome? 
> 
> For fragments that have configuration options, we are showing all possible combinations of them, so that users don’t miss anything. For the moment we are only taking into account configuration options of type select, but we may introduce improvements to this view in the future.



Thanks again for your work!

**Comment by Alec-Shay** [comment]
@sandrodw3 

> And just for curiosity, why we put `pages` in lowercase and `Page Templates` and the rest of types in uppercase?

To answer your question, this is due to our rules regarding terminology and Liferay when it refers to Liferay-specific features. If you're curious, you can see a brief explanation of it in our [standards document here](https://github.com/liferay/liferay-learn/blob/master/readme/WRITING_GUIDELINES.md#liferay-specific-examples). Basically, whenever we have a unique Liferay implementation of a feature (i.e., something we represent in our database with unique functionality to Liferay), we refer to it in upper case.

The "pages" example is one that we've debated on internally, but I believe our decision was that the regular use of "pages" is both generic (referring to the exact same thing inside and outside of Liferay) and frequent enough it doesn't warrant capitalization. However, if it were "Public Pages," "Private Pages," "Site Pages," etc., then in all of those cases we do capitalize it, because it is Liferay terminology.

**Comment by Alec-Shay** [comment]
Thanks for taking a look, and for the feedback, @sandrodw3! I'm making some changes per this suggestions and I'll go ahead and push this forward.

**Comment by sandrodw3** [comment]
I see @Alec-Shay! Now i have a better idea, thanks for the explanation 🥰
And thanks again for your work!

**Pull request closed without merging**
