### PR TITLE
LPS-117909 style books

### PR DESCRIPTION
**Pull request by Alec-Shay**
See: https://issues.liferay.com/browse/LPS-117909

This adds two new articles giving an overview of the Style Books feature. The first article ("Using a Style Book to Standardize Site Experience") is more oriented for end-users and covers creating a new Style Book in the UI, and selecting one for a page. The other article focuses on token definitions (more developer-oriented). 

There's also a placeholder already in place for a tentative future article giving a tutorial/walkthrough of adding a new token definition.

### CODE REVIEW

**Review by victorg1991 — COMMENTED** [review]
Looks super good overall, nice work!!

I think we should at least mention a couple of things

- Style Book inheritance, I think it is pretty straightforward how this works but I think it is worth mentioning it, don't you think?
- Mentioning which token definition is used in a site, as we cannot assign a theme to a site, the token definition is obtained from the theme applied to public pages, this is a bit tricky and a bit confusing so I believe this should be included in the docs. 

Does it make sense? We can arrange a call to explain these things further if you need it :)

Thanks!!

**Comment by Alec-Shay** [comment]
Thanks for the feedback, @victorg1991! After clarifying I've gone ahead and pushed up an update that hopefully addresses these concerns: https://github.com/Alec-Shay/liferay-learn/pull/62/commits/d5c3ec7048f581d1ea12b7aeac723cd50eca4a98

**Review by victorg1991 — APPROVED** [review]
Awesome! great work 🚀

**Comment by Alec-Shay** [comment]
Thanks! Moving forward in review with the KM team here: https://github.com/sez11a/liferay-learn/pull/258

**Pull request closed without merging**
