### PR TITLE
LRDOCS-8379 REST Builder

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8379

@brianchandotcom added his comments here: https://github.com/brianchandotcom/liferay-learn/pull/66. 

I'm sending this back to you because I'd moved the files around to match what @jrhoun, @ethanbustad, and I had defined for this section, so you'd have that as a starting point.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hey @sez11a,

I saw Brian's comments, and was expecting we might talk to him at some point, though I am not sure what happened there. Did you get a chance to talk to him about this?

I've been trying to make heads or tails of what he was asking for specifically, but I am a bit lost at the moment. In particular I am confused about whether I'm to take this and scrap the whole REST Builder thing and try to figure out what he means by an *Extension ([this](https://github.com/liferay-headless/liferay-portal/pull/232) was part of one of the tickets he linked, which seems like a whole different beast to try to understand), or if I should actually keep working with the ticket I was originally assigned to do (which was specifically to write an article on [this workflow](https://github.com/javierdearcos/rest-builder-docs/blob/master/REST%20Builder.md) for REST Builder), but just not with Journal.

**Comment by brianchandotcom** [comment]
Hey @Alec-Shay Call me on Slack anytime you're confused (especially since @sez11a is sick right now).

I basically just want a very simple REST builder example. The one with Journal as an extension was too much.

Just have a *ResourceImpl that takes "Foo" as a model, or "Hamburger". And allow CRUD on Hamburger, but just back it with a simple LinkedHashMap so that the example is super clear.

Foo/fooId, fooValue.

or

Hamburger/hamburgerId, boolean cheese, boolean extraMeat, etc. ec.

**Comment by sez11a** [comment]
@brianchandotcom I'm all right; I'm back at work. :-) @Alec-Shay I was remiss last week in meeting with you to discuss this, but I can do that this week whenever you're available. Brian just gave you the high level, though which might be enough. Let me know.

**Comment by Alec-Shay** [comment]
Thanks @brianchandotcom, I do think that helps clear up what my main point of confusion. I'll let you know if I am still unsure on any of that.

Glad to hear you're doing better now, too, @sez11a. And I'm also open at any point if you'd like to discuss further still, for the record, though I should be ready to start making the changes now.

**Comment by Alec-Shay** [comment]
Closing in favor of: https://github.com/sez11a/liferay-learn/pull/216

**Pull request closed without merging**
